google/GoogleAppMeasurement

Package.swift

The library itself is unchanged for 7.10.0

Update nanopb dep for 7.10.0

---

Package.swift

GoogleAppMeasurement SPM changes for 8.0.0

GoogleAppMeasurement 8.0.0

---

Package.swift

GoogleAppMeasurement SPM changes for 8.3.0

Analytics 8.3.0

---

Package.swift

Update GoogleAppMeasurement SPM changes for 8.3.0

Analytics update 8.3.0 SPM

---

Package.swift

Analytics 8.7.0

---

Package.swift

Analytics 8.8.0 Package.swift file

Release 8.8.0

---

Package.swift

Analytics 8.9.1 Package.swift file.

Release 8.9.1

---

Package.swift

GoogleAppMeasurement SPM changes for 8.12.0

Release 8.12.0

---

Package.swift

Release 8.14.0

---

Package.swift

Analytics 8.15.0

---

.github/workflows/spm.yml
GoogleAppMeasurementOnDeviceConversionWrapper/dummy.m
GoogleAppMeasurementOnDeviceConversionWrapper/include/dummy.h
Package.swift

Release 9.0.0

---

Package.swift

Release 9.1.0

---

Package.swift

Release 10.0.0

---

Package.swift

Analytics 10.1.0

---

Package.swift

Analytics 10.4.0

---

Package.swift

Release 10.6.0

---

Package.swift

Release 10.9.0

---

Package.swift

Release 10.10.0

---

Package.swift

Analytics 10.11.0

---

Package.swift

Release 10.12.0

---

Package.swift

Analytics 10.17.0

---

Package.swift

Analytics 10.17.0 RC1

---

Package.swift

Analytics 10.17.0 RC2

---

Package.swift

Release 10.20.0

---

Package.swift

Analytics 10.21.0

---

Package.swift

context: https://github.com/firebase/firebase-ios-sdk/issues/11490#issuecomment-1965996097

[nanopb] Bump nanopb version in Package.swift

---

Package.swift

Release 10.22.0

---

Package.swift

Release 10.22.1

---

Package.swift

Release 10.23.0

---

Package.swift

Release 10.23.1

---

Package.swift

Analytics 10.25.0

---

Package.swift

Analytics 10.27.0

---

Package.swift

Analytics 10.28.0

---

Package.swift

Placeholder release 11.0.0

---

Package.swift

Analytics 11.0.0

---

Package.swift

Analytics 11.0.0 (rc2)
Note: Reusing GoogleAppMeasurementOnDeviceConversion (rc1)

Release 11.0.0 (rc2)

---

Package.swift

Release 11.3.0

---

Package.swift

Release 11.4.0

---

Package.swift

Release 11.7.0

---

Package.swift

Analytics 11.9.0

---

Package.swift

Release 11.12.0

---

GoogleAppMeasurementCoreWrapper/dummy.m
GoogleAppMeasurementCoreWrapper/include/dummy.h
GoogleAppMeasurementIdentitySupportWrapper/dummy.m
GoogleAppMeasurementIdentitySupportWrapper/include/dummy.h
GoogleAppMeasurementOnDeviceConversionWrapper/dummy.m
GoogleAppMeasurementWithoutAdIdSupportWrapper/dummy.m
Package.swift

Update Package.swift. Includes new Core and IdentitySupport names. Includes GoogleAdsOnDeviceConversion dependency.

ODM2 open beta

---

Package.swift

Release 11.15.0

---

Package.swift

Release 12.0.0

---

Package.swift

Needed to bump the swift-tools-version for my previous PR to work, #97

[Infra] Update Package.swift

---

Package.swift

Release 12.1.0

---

Package.swift

Release 12.2.0
